version: '3'

services:
  fiber-money-manager-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - fiber-net

networks:
  fiber-net:
    name: fiber-net