version: '3'

services:
  "fiber-money-manager-api":
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - fiber
  "fiber-money-manager-api-2":
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    networks:
      - fiber
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "fiber-money-manager-api"
      - "fiber-money-manager-api-2"
    networks:
      - fiber

networks:
  fiber:
    driver: bridge